
#### 捕获错误

```
config('error', array(
	'start'=> false,
	//错误捕获开启
	'catch'=> true
	));
	
error(function($e){
	//两种方式打印 错误信息
	//1) 闭包函数传进来的$e 错误信息
	//2) error() 获取错误信息，与$e等价的
	
	printexit(error(), $e);
});

//函数不存在，报错，会跳跃到 错误2的函数中
a();
```


```
/* ******************** 打印结果 ******************** */
Array (
    [title] => 致命性的运行时错误 - E_ERROR
    [type] => 1
    [message] => Call to undefined function a()
    [file] => Z:\WWW\website\localhost\index.php
    [line] => 50
    [location] => Z:\WWW\website\localhost\index.php 所在 50 行
    [backtrace] => Array
        (
            [0] => [ Z:\WWW\website\framework\cao.php 所在 1904 行 ] framework\cao::_debug_file_backtrace()
        )

)
```




#### 错误只能捕获一次

```
config('error', array(
	'start'=> false,
	//错误捕获开启
	'catch'=> true
	));
	
//错误1
error(function($e){
	printexit('错误1', $e);
});

//错误2
error(function($e){
	//函数不存在，报错，注意这里报错了那么就不再跳跃了
	a();
	printexit('错误2',$e);
});

//函数不存在，报错，会跳跃到 错误2的函数中
a();
```

> 在错误函数中出错，那么就是原生php错误，输出结果：


```
/* ******************** 打印结果 ******************** */
Fatal error: Call to undefined function a() in Z:\WWW\website\localhost\index.php on line 51
```
